version: "3"

volumes:
  public:

networks:
  development:
    driver: "bridge"

services:
  web:
    build:
      context: "."
      dockerfile: "config/docker/Dockerfile.dev"
      args:
        - NODE_ENV
    volumes:
      - ".:/www/src"
      - "public:/www/public"
    networks:
      - "development"

  nginx:
    build:
      context: "./config/nginx"
      dockerfile: "Dockerfile.dev"
    volumes:
      - "public:/www/public"
    networks:
      - "development"
    ports:
      - "80:80"
      - "443:443"
