// flow-typed signature: 8df134474823ec6a3b8f3a654e383c75
// flow-typed version: <<STUB>>/eslint-import-resolver-babel-module_v3.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-babel-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-babel-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-babel-module/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-babel-module/lib/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/lib/index'>;
}
