// flow-typed signature: 0a2dfa13532b6e3ebe1fa10c98d27a9e
// flow-typed version: <<STUB>>/moveto_v1.7.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moveto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moveto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moveto/dist/moveTo' {
  declare module.exports: any;
}

declare module 'moveto/dist/moveTo.min' {
  declare module.exports: any;
}

declare module 'moveto/gulpfile' {
  declare module.exports: any;
}

declare module 'moveto/src/moveTo' {
  declare module.exports: any;
}

declare module 'moveto/tests/moveTo-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moveto/dist/moveTo.js' {
  declare module.exports: $Exports<'moveto/dist/moveTo'>;
}
declare module 'moveto/dist/moveTo.min.js' {
  declare module.exports: $Exports<'moveto/dist/moveTo.min'>;
}
declare module 'moveto/gulpfile.js' {
  declare module.exports: $Exports<'moveto/gulpfile'>;
}
declare module 'moveto/src/moveTo.js' {
  declare module.exports: $Exports<'moveto/src/moveTo'>;
}
declare module 'moveto/tests/moveTo-spec.js' {
  declare module.exports: $Exports<'moveto/tests/moveTo-spec'>;
}
