// flow-typed signature: ed93d5c40179ddf359388cd84360e4a5
// flow-typed version: <<STUB>>/postcss-hexrgba_v0.2.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-hexrgba'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-hexrgba' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-hexrgba/index' {
  declare module.exports: $Exports<'postcss-hexrgba'>;
}
declare module 'postcss-hexrgba/index.js' {
  declare module.exports: $Exports<'postcss-hexrgba'>;
}
