FROM ubuntu:16.04

RUN \
  apt-get update && \
  apt-get install -y curl apt-transport-https && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
  apt-get install -y \
    nodejs \
    yarn \
    python \
    build-essential

ENV SRC=/www/src
ENV DEPS=/www/deps

RUN mkdir -p $DEPS
COPY package.json yarn.lock $DEPS/
RUN cd $DEPS && yarn

RUN mkdir -p $SRC
WORKDIR $SRC

ARG NODE_ENV

ENV NODE_ENV=$NODE_ENV
ENV WEB_HOSTNAME="alexfedoseev.dev"
ENV HOT_HOSTNAME="hot.alexfedoseev.dev"
ENV WEB_PORT="3000"
ENV HOT_PORT="3500"
ENV GOOGLE_ANALYTICS_ID="UA-36704000-8"
ENV FACEBOOK_APP_ID="597319510289959"

COPY scripts/entrypoint /entrypoint
RUN chmod +x /entrypoint

ENTRYPOINT ["/entrypoint"]
ENV BABEL_ENV=server
CMD ["scripts/start"]
