#!/usr/bin/env node

require('babel-register');

const webpack = require('webpack');
const nodemon = require('nodemon');
const cp = require('child_process');
const fs = require('fs');
const path = require('path');

const serverConfig = require('../config/webpack/server.babel').default;

const root = process.cwd();
const { NODE_ENV } = process.env;

const isDevelopment = NODE_ENV !== 'production';

const clean = () => {
  console.log('=> 🗑  Cleaning...');
  const cleanScript = path.resolve(root, 'scripts', 'clean');
  cp.exec(cleanScript);
  console.log('=> 🗑  Cleaned');
};

const compileAndWatchServerBuild = (config) => {
  console.log('=> 🔨  Compiling server development build...');

  let initialCompile = true;

  return new Promise(resolve => {
    webpack(config).watch(null, (error, stats) => {
      if (error) return console.error(error);

      if (initialCompile) {
        initialCompile = false;
        console.log('=> 🔨  Server development build is compiled');
        return resolve();
      }

      return false;
    });
  });
};

const compileProductionBuilds = () => new Promise(resolve => {
  console.log('=> 🔨  Compiling production builds...');
  const buildScript = path.resolve(root, 'scripts', 'build');

  cp
    .spawn(buildScript, [], { stdio: 'inherit' })
    .on('exit', () => {
      console.log('=> 🔨  Production builds are compiled');
      resolve();
    });
});

const runHotServer = () => new Promise(resolve => {
  console.log('=> 🔥  Starting HOT server...');
  const hotServer = path.resolve(root, 'scripts', 'start:hot');

  cp
    .fork(hotServer)
    .on('message', () => {
      console.log('=> 🔥  Client development builds are compiled');
      resolve();
    });
});

const runAppServer = () => {
  console.log('=> 🚀  Starting WEB server...');

  const app = path.resolve(root, 'build', 'app.js');
  const templates = path.resolve(root, 'app', 'shell', 'server', 'templates');
  const manifest = path.resolve(root, 'public', 'assets', 'modules.manifest.json');

  if (!fs.existsSync(app)) {
    console.error(`🚨  Can't find app build at path: ${app}`);
    process.exit(1);
  }

  if (!fs.existsSync(templates)) {
    console.error(`🚨  Can't find directory with server templates at path: ${templates}`);
    process.exit(1);
  }

  if (!fs.existsSync(manifest)) {
    console.error(`🚨  Can't find modules manifest at path: ${manifest}`);
    process.exit(1);
  }

  nodemon({
    script: app,
    watch: [app, templates, manifest],
    ext: 'js json',
  });
};

const runDevelopment = async () => {
  await clean();
  await runHotServer();
  await compileAndWatchServerBuild(serverConfig);
  await runAppServer();
};

const runProduction = async () => {
  await clean();
  await compileProductionBuilds();
  await runAppServer();
};

isDevelopment ? runDevelopment() : runProduction();
